[build]
  publish = "bin/Release/net8.0/publish/wwwroot"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/json"

[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Content-Type = "application/javascript"
